{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "schema",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.0.1.jar",
          "url": "schema-0.0.1.jar",
          "size": 11015,
          "sha512": "96ac6686f6014b1cec65cc0b0de3b0b88dada4728425019dbdd94e956e1c05d5fc46071a3109eade4217f878b7c3bd3b5b735dc51c9912d2466faa401131f42a",
          "sha256": "33d11d9b96fc164432d071b6341b68e18e5837ddcf8ded50559945197046a444",
          "sha1": "c1cda9abf6623971b8a6be355fc167350ac79ee6",
          "md5": "1ab534aa369ee4e9f0d3675364fd960b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.0.1.jar",
          "url": "schema-0.0.1.jar",
          "size": 11015,
          "sha512": "96ac6686f6014b1cec65cc0b0de3b0b88dada4728425019dbdd94e956e1c05d5fc46071a3109eade4217f878b7c3bd3b5b735dc51c9912d2466faa401131f42a",
          "sha256": "33d11d9b96fc164432d071b6341b68e18e5837ddcf8ded50559945197046a444",
          "sha1": "c1cda9abf6623971b8a6be355fc167350ac79ee6",
          "md5": "1ab534aa369ee4e9f0d3675364fd960b"
        }
      ]
    }
  ]
}
