{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "schema-apollo",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apolloServiceProducer",
      "attributes": {
        "com.apollographql.service": "service",
        "org.gradle.usage": "apollo-metadata"
      },
      "files": [
        {
          "name": "schema-apollo-0.0.1-service.json",
          "url": "schema-apollo-0.0.1-service.json",
          "size": 5673,
          "sha512": "fcc6ebc90e2c73c44ea2e645703923e05424bc66afb277df1f0a09f78f5b67d7c7541352b1debbfff8d12aee66e26614352253863ff40c257626af37b79aeeaa",
          "sha256": "0d7742734950ade2ee29c5b5a2ee18efdeb27f0063e502c325b605e7a68bc824",
          "sha1": "44d2950e94c8a0a9098ff6938fdede8c0cb55ecb",
          "md5": "379e5384f82d1afaf01a0e71566ce4a2"
        }
      ]
    }
  ]
}
